export default
[
   {
      "id":19169,
      "name":"Raw Data",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"8phhKZn4DuM"
         },
         {
            "name":"Gameplay video",
            "video_id":"yspH06z0UQU"
         },
         {
            "name":"Trailer",
            "video_id":"qYjYEgo_rkI"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/bgsqkm80ofh3vru71sic.png",
         "cloudinary_id":"bgsqkm80ofh3vru71sic",
         "width":310,
         "height":310
      }
   },
   {
      "id":25960,
      "name":"Super Dot Jump",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/qnulu5ep3oc1hbmhhrvo.png",
         "cloudinary_id":"qnulu5ep3oc1hbmhhrvo",
         "width":393,
         "height":96
      }
   },
   {
      "id":14047,
      "name":"Two Dots",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/rg4iwwhvcmat6muzbdsp.png",
         "cloudinary_id":"rg4iwwhvcmat6muzbdsp",
         "width":175,
         "height":175
      }
   },
   {
      "id":10168,
      "name":"Data Hacker: Reboot",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/hxb46krapdpuzhohpjdq.png",
         "cloudinary_id":"hxb46krapdpuzhohpjdq",
         "width":460,
         "height":215
      }
   },
   {
      "id":8211,
      "name":"Dead or Alive 5: Last Round",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"Iamz80-bUnI"
         },
         {
            "name":"Last Fight Trailer",
            "video_id":"5_f8KwO_xwE"
         },
         {
            "name":"Launch Trailer",
            "video_id":"kdJGnOML2P8"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/nvivsmnd9zjlbgawcdz6.png",
         "cloudinary_id":"nvivsmnd9zjlbgawcdz6",
         "width":3508,
         "height":4961
      }
   },
   {
      "id":3187,
      "name":"Shroud of the Avatar: Forsaken Virtues",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"gSZLrF657yo"
         },
         {
            "name":"Gameplay video",
            "video_id":"n8tKuMvUYzY"
         },
         {
            "name":"Gameplay video",
            "video_id":"yGa6hR4a87U"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/njfaaccsxkaedupnplcf.png",
         "cloudinary_id":"njfaaccsxkaedupnplcf",
         "width":640,
         "height":480
      }
   },
   {
      "id":9683,
      "name":"Dungeon of the Endless",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"qplvDyEQr1M"
         },
         {
            "name":"Teaser",
            "video_id":"K2aQYDmsocQ"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/sz77k6xj4anqya1xtdav.png",
         "cloudinary_id":"sz77k6xj4anqya1xtdav",
         "width":1000,
         "height":1000
      }
   },
   {
      "id":17954,
      "name":"Data Hacker: Corruption",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/kipadidzr0ufdyxcn9a4.png",
         "cloudinary_id":"kipadidzr0ufdyxcn9a4",
         "width":460,
         "height":215
      }
   },
   {
      "id":10167,
      "name":"Data Hacker Initiation",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/qnz5aikzkbirlgoabl3j.png",
         "cloudinary_id":"qnz5aikzkbirlgoabl3j",
         "width":480,
         "height":600
      }
   },
   {
      "id":7286,
      "name":"Dead or Alive 5 Ultimate",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"SipYi8XOUBo"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/njujcqupitkkmpoopmcq.png",
         "cloudinary_id":"njujcqupitkkmpoopmcq",
         "width":256,
         "height":297
      }
   },
   {
      "id":2963,
      "name":"DOTA 2",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"-cSFPIwMEq4"
         },
         {
            "name":"Gameplay video",
            "video_id":"-8HBr1EGX1I"
         },
         {
            "name":"Trailer",
            "video_id":"Cp8neRiF9-k"
         },
         {
            "name":"Trailer",
            "video_id":"0g5NpKONAmk"
         },
         {
            "name":"Trailer",
            "video_id":"8Kqap9-NWD8"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/ebyoyogasgtr71mhj5ce.png",
         "cloudinary_id":"ebyoyogasgtr71mhj5ce",
         "width":272,
         "height":380
      }
   },
   {
      "id":11725,
      "name":"Dead or Alive 5 Plus",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"Cf-aa5RU_VY"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/miw4lms0usrizvvyresl.png",
         "cloudinary_id":"miw4lms0usrizvvyresl",
         "width":640,
         "height":817
      }
   },
   {
      "id":7980,
      "name":"Team Umizoomi & Dora's Fantastic Flight",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/k3otjxqcceuokpo9l1r7.png",
         "cloudinary_id":"k3otjxqcceuokpo9l1r7",
         "width":270,
         "height":245
      }
   },
   {
      "id":1383,
      "name":"Dead or Alive 5",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"5pgsgmpoy1g"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/dr7h3i9refwjxtemxwus.png",
         "cloudinary_id":"dr7h3i9refwjxtemxwus",
         "width":640,
         "height":903
      }
   },
   {
      "id":19383,
      "name":"Dot by Dot+"
   },
   {
      "id":15145,
      "name":"Data Jammers: FastForward"
   },
   {
      "id":7976,
      "name":"Dora Puppy",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/ewar90zawavxru52ulgp.png",
         "cloudinary_id":"ewar90zawavxru52ulgp",
         "width":236,
         "height":213
      }
   },
   {
      "id":7978,
      "name":"Dora the Explorer: Dora's Cooking Club",
      "videos":[
         {
            "name":"Gameplay video",
            "video_id":"NncQae-SYTE"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/sqnehyg3e6ksqz6qhlju.png",
         "cloudinary_id":"sqnehyg3e6ksqz6qhlju",
         "width":237,
         "height":212
      }
   },
   {
      "id":7265,
      "name":"3D Dot Game Heroes",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"hoFYEtj2tDw"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/yu94dc3ooad70fqqi7i9.png",
         "cloudinary_id":"yu94dc3ooad70fqqi7i9",
         "width":256,
         "height":295
      }
   },
   {
      "id":4793,
      "name":"Data East Arcade Classics",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/fnftfrh5e3xjnigti7du.png",
         "cloudinary_id":"fnftfrh5e3xjnigti7du",
         "width":189,
         "height":266
      }
   },
   {
      "id":7977,
      "name":"Dora the Exporer: Dora Saves the Crystal Kingdom",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/g8mozonoqbqmzx6ijhfd.png",
         "cloudinary_id":"g8mozonoqbqmzx6ijhfd",
         "width":189,
         "height":266
      }
   },
   {
      "id":9739,
      "name":"Crossfire",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"eRCInSmRfUw"
         },
         {
            "name":"Gameplay video",
            "video_id":"beMD1tv3BjI"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/dppifgr97v87t53dlk5i.png",
         "cloudinary_id":"dppifgr97v87t53dlk5i",
         "width":800,
         "height":501
      }
   },
   {
      "id":7975,
      "name":"Dora the Explorer: Dora Saves the Mermaids",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/fghp4na5akvrq04g95ex.png",
         "cloudinary_id":"fghp4na5akvrq04g95ex",
         "width":165,
         "height":148
      }
   },
   {
      "id":1392,
      "name":"Dead or Alive 4",
      "videos":[
         {
            "name":"Trailer",
            "video_id":"NzSgf28U56U"
         }
      ],
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/kabfafpiuvwh6lm1fn87.png",
         "cloudinary_id":"kabfafpiuvwh6lm1fn87",
         "width":694,
         "height":877
      }
   },
   {
      "id":3892,
      "name":"Dora the Explorer: Journey to the Purple Planet",
      "cover":{
         "url":"//images.igdb.com/igdb/image/upload/t_thumb/ndbex4hk80hjjbwp7qgm.png",
         "cloudinary_id":"ndbex4hk80hjjbwp7qgm",
         "width":188,
         "height":268
      }
   }
]
